In [13]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/ddos-sdn-dataset/dataset_sdn.csv


## 1. Dataset

In [4]:
data = pd.read_csv("/kaggle/input/ddos-sdn-dataset/dataset_sdn.csv")
data.head()

dt  switch       src       dst  pktcount  bytecount  dur   dur_nsec  \
0  11425       1  10.0.0.1  10.0.0.8     45304   48294064  100  716000000   
1  11605       1  10.0.0.1  10.0.0.8    126395  134737070  280  734000000   
2  11425       1  10.0.0.2  10.0.0.8     90333   96294978  200  744000000   
3  11425       1  10.0.0.2  10.0.0.8     90333   96294978  200  744000000   
4  11425       1  10.0.0.2  10.0.0.8     90333   96294978  200  744000000   

        tot_dur  flows  ...  pktrate  Pairflow  Protocol  port_no   tx_bytes  \
0  1.010000e+11      3  ...      451         0       UDP        3  143928631   
1  2.810000e+11      2  ...      451         0       UDP        4       3842   
2  2.010000e+11      3  ...      451         0       UDP        1       3795   
3  2.010000e+11      3  ...      451         0       UDP        2       3688   
4  2.010000e+11      3  ...      451         0       UDP        3       3413   

  rx_bytes  tx_kbps  rx_kbps  tot_kbps  label  
0     3917        0      0.0       0.0      0  
1     3520        0      0.0       0.0      0  
2     1242        0      0.0       0.0      0  
3     1492        0      0.0       0.0      0  
4     3665        0      0.0       0.0      0  

[5 rows x 23 columns]

## 2. Data Pre-Processing

In [6]:
df1 = data.copy(deep=True)
df1 = df1.dropna()
df1.head()


dt  switch       src       dst  pktcount  bytecount  dur   dur_nsec  \
0  11425       1  10.0.0.1  10.0.0.8     45304   48294064  100  716000000   
1  11605       1  10.0.0.1  10.0.0.8    126395  134737070  280  734000000   
2  11425       1  10.0.0.2  10.0.0.8     90333   96294978  200  744000000   
3  11425       1  10.0.0.2  10.0.0.8     90333   96294978  200  744000000   
4  11425       1  10.0.0.2  10.0.0.8     90333   96294978  200  744000000   

        tot_dur  flows  ...  pktrate  Pairflow  Protocol  port_no   tx_bytes  \
0  1.010000e+11      3  ...      451         0       UDP        3  143928631   
1  2.810000e+11      2  ...      451         0       UDP        4       3842   
2  2.010000e+11      3  ...      451         0       UDP        1       3795   
3  2.010000e+11      3  ...      451         0       UDP        2       3688   
4  2.010000e+11      3  ...      451         0       UDP        3       3413   

  rx_bytes  tx_kbps  rx_kbps  tot_kbps  label  
0     3917        0      0.0       0.0      0  
1     3520        0      0.0       0.0      0  
2     1242        0      0.0       0.0      0  
3     1492        0      0.0       0.0      0  
4     3665        0      0.0       0.0      0  

[5 rows x 23 columns]

In [8]:
m,n = df1.shape
print(f"No. of training examples: {m}")
print(f"No. of features: {n-1}") # (n-1) because last column is label/ target

No. of training examples: 103839
No. of features: 22


In [27]:
y = df1["label"]
y.head()

0    0
1    0
2    0
3    0
4    0
Name: label, dtype: int64

In [11]:
X = df1.drop(['dt','src','dst','label'], axis=1)
X.head()

switch  pktcount  bytecount  dur   dur_nsec       tot_dur  flows  \
0       1     45304   48294064  100  716000000  1.010000e+11      3   
1       1    126395  134737070  280  734000000  2.810000e+11      2   
2       1     90333   96294978  200  744000000  2.010000e+11      3   
3       1     90333   96294978  200  744000000  2.010000e+11      3   
4       1     90333   96294978  200  744000000  2.010000e+11      3   

   packetins  pktperflow  byteperflow  pktrate  Pairflow Protocol  port_no  \
0       1943       13535     14428310      451         0      UDP        3   
1       1943       13531     14424046      451         0      UDP        4   
2       1943       13534     14427244      451         0      UDP        1   
3       1943       13534     14427244      451         0      UDP        2   
4       1943       13534     14427244      451         0      UDP        3   

    tx_bytes  rx_bytes  tx_kbps  rx_kbps  tot_kbps  
0  143928631      3917        0      0.0       0.0  
1       3842      3520        0      0.0       0.0  
2       3795      1242        0      0.0       0.0  
3       3688      1492        0      0.0       0.0  
4       3413      3665        0      0.0       0.0

In [12]:
# convert categorial data into dummy variables
X = pd.get_dummies(X)
X.head()

switch  pktcount  bytecount  dur   dur_nsec       tot_dur  flows  \
0       1     45304   48294064  100  716000000  1.010000e+11      3   
1       1    126395  134737070  280  734000000  2.810000e+11      2   
2       1     90333   96294978  200  744000000  2.010000e+11      3   
3       1     90333   96294978  200  744000000  2.010000e+11      3   
4       1     90333   96294978  200  744000000  2.010000e+11      3   

   packetins  pktperflow  byteperflow  ...  Pairflow  port_no   tx_bytes  \
0       1943       13535     14428310  ...         0        3  143928631   
1       1943       13531     14424046  ...         0        4       3842   
2       1943       13534     14427244  ...         0        1       3795   
3       1943       13534     14427244  ...         0        2       3688   
4       1943       13534     14427244  ...         0        3       3413   

   rx_bytes  tx_kbps  rx_kbps  tot_kbps  Protocol_ICMP  Protocol_TCP  \
0      3917        0      0.0       0.0              0             0   
1      3520        0      0.0       0.0              0             0   
2      1242        0      0.0       0.0              0             0   
3      1492        0      0.0       0.0              0             0   
4      3665        0      0.0       0.0              0             0   

   Protocol_UDP  
0             1  
1             1  
2             1  
3             1  
4             1  

[5 rows x 21 columns]

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
                                    X, y, test_size=0.2, random_state=46
)
X_train.head()

switch  pktcount  bytecount  dur   dur_nsec       tot_dur  flows  \
34957       4     74771    4037634  243  630000000  2.440000e+11      4   
59277       4       749      73402  768  384000000  7.680000e+11      7   
63625       4        19       1862   19  930000000  1.993000e+10     11   
35540       2     28016   31448128   64  361000000  6.436100e+10      4   
53330       2       303      29694  310  921000000  3.110000e+11      7   

       packetins  pktperflow  byteperflow  ...  Pairflow  port_no   tx_bytes  \
34957       4357        8899       480546  ...         1        3  160775993   
59277       3028          29         2842  ...         1        1      10267   
63625       1069           0            0  ...         1        1  271150956   
35540       4918       13081     14672338  ...         1        2   14131436   
53330       2800          29         2842  ...         1        3  271215451   

        rx_bytes  tx_kbps  rx_kbps  tot_kbps  Protocol_ICMP  Protocol_TCP  \
34957   11645601      380    135.0     515.0              0             1   
59277       6212        0      0.0       0.0              1             0   
63625  271134152        3      3.0       6.0              1             0   
35540  325695770      160   3918.0    4078.0              0             1   
53330     296905        1      1.0       2.0              1             0   

       Protocol_UDP  
34957             0  
59277             0  
63625             0  
35540             0  
53330             0  

[5 rows x 21 columns]

## 3. Importing Required Classes from TensorFlow

In [29]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

## 4. Normalizing the data

In [36]:
norm_layer = tf.keras.layers.Normalization(axis=-1)
norm_layer.adapt(X_train)  # learns mean and variance implicitly
X_norm = norm_layer(X_train)

In [37]:
X_norm

<tf.Tensor: shape=(83071, 21), dtype=float32, numpy=
array([[-0.1115431 ,  0.42389682, -0.69524884, ..., -0.81254476,
         1.5827115 , -0.68129915],
       [-0.1115431 , -0.9984426 , -0.7765677 , ...,  1.2307099 ,
        -0.63183093, -0.68129915],
       [-0.1115431 , -1.0124696 , -0.7780351 , ...,  1.2307099 ,
        -0.63183093, -0.68129915],
       ...,
       [ 0.9080417 , -0.90847754, -0.6619874 , ..., -0.81254476,
        -0.63183093,  1.4677905 ],
       [-0.1115431 , -0.99436903, -0.7761415 , ...,  1.2307099 ,
        -0.63183093, -0.68129915],
       [-0.6213355 ,  0.17940402, -0.69406646, ..., -0.81254476,
         1.5827115 , -0.68129915]], dtype=float32)>

## 5. Building the NN Model

In [31]:
model = tf.keras.models.Sequential(
    [
        tf.keras.Input(shape=(21,)),
        Dense(10, activation="relu", name="Layer1"),
        Dense(10, activation="relu", name="Layer2"),
        Dense(1, activation="sigmoid", name="Layer3")
    ], name="my_model"
)

In [32]:
model.summary()

Model: "my_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Layer1 (Dense)              (None, 10)                220       
                                                                 
 Layer2 (Dense)              (None, 10)                110       
                                                                 
 Layer3 (Dense)              (None, 1)                 11        
                                                                 
Total params: 341
Trainable params: 341
Non-trainable params: 0
_________________________________________________________________


In [33]:
# Initial Weights and bias
W1, b1 = model.get_layer("Layer1").get_weights()
W2, b2 = model.get_layer("Layer2").get_weights()
W3, b3 = model.get_layer("Layer3").get_weights()
print(f"W1: {W1.shape}")
print(f"b1: {b1.shape}")
print(f"W2: {W2.shape}")
print(f"b2: {b2.shape}")
print(f"W3: {W3.shape}")
print(f"b3: {b3.shape}")

W1: (21, 10)
b1: (10,)
W2: (10, 10)
b2: (10,)
W3: (10, 1)
b3: (1,)


In [39]:
model.compile(
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
    loss = tf.keras.losses.BinaryCrossentropy()
)

model.fit(
    X_norm,
    y_train,
    epochs=15,
)

Epoch 1/15
2596/2596 [==============================] - 6s 2ms/step - loss: 0.0346
Epoch 2/15
2596/2596 [==============================] - 5s 2ms/step - loss: 0.0346
Epoch 3/15
2596/2596 [==============================] - 5s 2ms/step - loss: 0.0336
Epoch 4/15
2596/2596 [==============================] - 5s 2ms/step - loss: 0.0342
Epoch 5/15
2596/2596 [==============================] - 5s 2ms/step - loss: 0.0325
Epoch 6/15
2596/2596 [==============================] - 5s 2ms/step - loss: 0.0324
Epoch 7/15
2596/2596 [==============================] - 5s 2ms/step - loss: 0.0307
Epoch 8/15
2596/2596 [==============================] - 5s 2ms/step - loss: 0.0331
Epoch 9/15
2596/2596 [==============================] - 5s 2ms/step - loss: 0.0298
Epoch 10/15
2596/2596 [==============================] - 5s 2ms/step - loss: 0.0294
Epoch 11/15
2596/2596 [==============================] - 5s 2ms/step - loss: 0.0309
Epoch 12/15
2596/2596 [==============================] - 5s 2ms/step - loss: 0.0300
E

## 6. Prediction and Accuracy using Test Set

In [40]:
# normalize the test set
X_test_norm = norm_layer(X_test)
X_test_norm

<tf.Tensor: shape=(20768, 21), dtype=float32, numpy=
array([[-1.131128  , -0.7858084 , -0.5197147 , ..., -0.81254476,
        -0.63183093,  1.4677905 ],
       [-0.6213355 ,  3.0360155 , -0.5446657 , ..., -0.81254476,
         1.5827115 , -0.68129915],
       [ 0.3982493 , -1.0070125 , -0.7774642 , ...,  1.2307099 ,
        -0.63183093, -0.68129915],
       ...,
       [-1.131128  ,  1.4849926 , -0.63407886, ..., -0.81254476,
         1.5827115 , -0.68129915],
       [-0.6213355 , -0.9939847 , -0.7761013 , ...,  1.2307099 ,
        -0.63183093, -0.68129915],
       [-1.6409203 , -0.43198174, -0.11705564, ..., -0.81254476,
        -0.63183093,  1.4677905 ]], dtype=float32)>

In [48]:
predictions = model.predict(X_test_norm)
y_hat = (predictions >= 0.5).astype(int)

649/649 [==============================] - 1s 1ms/step


In [51]:
print(y_test[0:10])
print(y_hat[0:10])

21869     1
84301     1
49915     0
54047     0
102167    0
97629     0
89480     1
93926     1
39822     1
26851     0
Name: label, dtype: int64
[[1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]]


In [46]:
# Accuracy 
m = tf.keras.metrics.BinaryAccuracy()
m.reset_state()
m.update_state(y_test, predictions)
accuracy = m.result().numpy()
print(f"Accuracy achieved: {accuracy:0.4f}")

Accuracy achieved: 0.9896
